"""Added branch stock count table

Revision ID: 4ab995113fa7
Revises: 5ba2ee98ba3c
Create Date: 2025-04-02 19:28:05.853627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab995113fa7'
down_revision = '5ba2ee98ba3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branchstockcount',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Float(), nullable=False),
    sa.Column('ordered_qty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventoryitems.item_id'], ),
    sa.PrimaryKeyConstraint('branch_id', 'item_id')
    )
    op.create_table('product_tags',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tags')
    op.drop_table('branchstockcount')
    # ### end Alembic commands ###
