"""Add unique constraint to branch_id and item_id

Revision ID: 792c573c655c
Revises: 4ab995113fa7
Create Date: 2025-04-09 18:23:30.593903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792c573c655c'
down_revision = '4ab995113fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branchstockcount', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_branch_item', ['branch_id', 'item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branchstockcount', schema=None) as batch_op:
        batch_op.drop_constraint('unique_branch_item', type_='unique')

    # ### end Alembic commands ###
